# Generated by Django 5.1.2 on 2024-10-13 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('LGBT', 'LGBT')], max_length=10)),
                ('contact_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('I', 'Independent Elderly'), ('P', 'Partially Dependent Elderly'), ('F', 'Fully Dependent Elderly'), ('B', 'Bedridden Elderly'), ('D', 'Dementia Elderly')], max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
